/* tslint:disable */
/* eslint-disable */
/**
 * Blog API
 * API for managing blog posts with MDX content parsing
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProblemDetails,
  WeatherForecast,
} from '../models/index';
import {
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    WeatherForecastFromJSON,
    WeatherForecastToJSON,
} from '../models/index';

/**
 * 
 */
export class WeatherApi extends runtime.BaseAPI {

    /**
     * Retrieves weather forecast data for the next 5 days with randomly generated temperatures and weather conditions
     * Get 5-day weather forecast
     */
    async getWeatherForecastRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WeatherForecast>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/WeatherForecast`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WeatherForecastFromJSON));
    }

    /**
     * Retrieves weather forecast data for the next 5 days with randomly generated temperatures and weather conditions
     * Get 5-day weather forecast
     */
    async getWeatherForecast(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WeatherForecast>> {
        const response = await this.getWeatherForecastRaw(initOverrides);
        return await response.value();
    }

}
